services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  
  web:
    platform: linux/x86_64
    image: nginx:latest
    ports:
      - '80:80'
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
      - ${DOCKER_SCRATCH_DIR}:/scratch
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
      - postgres
      - elasticsearch
      - beanstalkd
    links:
      - php-fpm
  beanstalkd:
    platform: linux/x86_64
    image: maateen/docker-beanstalkd
    ports:
      - "11300:11300"
  php-fpm:
    platform: linux/x86_64
    build: 
      context: .
      args:
        - DOCKER_SCRATCH_DIR=${DOCKER_SCRATCH_DIR}
        - DOCKER_ENVIRONMENT=${ENVIRONMENT}
        - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ${DOCKER_SCRATCH_DIR}:/scratch
      - /var/run/docker.sock:/var/run/docker.sock
    develop:
      watch:
        - action: sync
          path: ./
          target: /var/www/html/
          ignore:
            - vendor/
  # apache:
  #   platform: linux/x86_64
  #   build: 
  #     context: .
  #     args:
  #       - DOCKER_SCRATCH_DIR=${DOCKER_SCRATCH_DIR}
  #       - DOCKER_ENVIRONMENT=${ENVIRONMENT}
  #       - ENVIRONMENT=${ENVIRONMENT}
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - .:/var/www/html
  #     - ${DOCKER_SCRATCH_DIR}:/scratch
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - redis
  #     - postgres
  #     - beanstalkd
  #     - elasticsearch
  
  elasticsearch:
    platform: linux/x86_64
    image: elasticsearch:5.6.16
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  postgres-data:
  elasticsearch-data:
