<?php

declare(strict_types=1);

namespace Elevator\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250306122754 extends AbstractMigration
{
    private $tables_to_migrate;
    public function __construct()
    {
        $this->tables_to_migrate = [
            'api_keys',
            'asset_cache',
            'assets',
            'collection_permissions',
            'collections',
            'csv_batches',
            'custom_search',
            'drawer_groups',
            'drawer_items',
            'drawer_permissions',
            'drawers',
            'field_types',
            'filehandlers',
            'group_entry',
            'instance_groups',
            'instance_handler_permissions',
            'instance_pages',
            'instance_permissions',
            'instances',
            'job_logs',
            'logs',
            'lti13_deployments',
            'lti13_instance_association',
            'lti13_issuers',
            'lti13_resource_links',
            'permissions',
            'recent_collection',
            'recent_drawer',
            'templates',
            'uploads',
            'users',
            'widgets'
        ];

    }

    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        
      
        foreach($this->tables_to_migrate as $table) {
            $columnCheck = $this->connection->fetchOne("SELECT is_identity FROM information_schema.columns WHERE table_name = '$table' AND column_name = 'id'");
            if ($columnCheck !== 'YES') {
                $this->addSql('DROP SEQUENCE elevator.' . $table . '_id_seq CASCADE');
                $this->addSql('ALTER TABLE ' . $table . ' ALTER COLUMN id TYPE INT');
                $this->addSql('ALTER TABLE ' . $table . ' ALTER COLUMN id DROP DEFAULT');
                $this->addSql('ALTER TABLE ' . $table . ' ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
                $this->addSql('SELECT setval(pg_get_serial_sequence(\'' . $table . '\', \'id\'), (SELECT MAX(id) FROM ' . $table . ') + 1, false);');
            }
        }
        
    }

    public function down(Schema $schema): void
    {

        foreach($this->tables_to_migrate as $table) {
            $this->addSql('ALTER TABLE ' . $table .' ALTER COLUMN id DROP IDENTITY');

            $this->addSql('DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = \'' . $table . '_id_seq\') THEN CREATE SEQUENCE elevator.' . $table . '_id_seq INCREMENT BY 1 MINVALUE 1 START 1; END IF; END $$;');

            $this->addSql('ALTER TABLE '. $table . ' ALTER COLUMN id SET DEFAULT nextval(\'elevator.' . $table . '_id_seq\')');

            $this->addSql('SELECT setval(\'elevator.' . $table . '_id_seq\', (SELECT COALESCE(MAX(id), 1)+1 FROM ' . $table . '), false);');
        }


    }
}
