<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/

if(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on"){
	$ssl_set = "s";
}
else{
	$ssl_set = "";
}


if(isset($_SERVER['HTTP_HOST'])) {
	$config['base_url'] = 'https://' .$_SERVER['HTTP_HOST'] ."/";
}
else {
    if(isset($_SERVER['CLI_SERVERNAME'])) {
        $config['base_url'] = "https://" . $_SERVER['CLI_SERVERNAME'] . "/";
    }
    else {
	    $config['base_url'] = "http://localhost" . "/"; // full address http://www.test.com/
    }
}


//$config['base_url']	= 'http://localhost/dcl3/';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']	= 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = TRUE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = $_SERVER['ENCRYPTION_KEY'] ?? '';
/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']		= 'ci_session';
$config['sess_expiration']		= 3600;
$config['sess_expire_on_close']	= FALSE;
$config['sess_encrypt_cookie']	= TRUE;
$config['sess_use_database']	= FALSE;
$config['sess_table_name']		= 'ci_sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 86400;
$config['sess_driver'] = 'redis';
$config['sess_save_path'] = 'tcp://' . ($_SERVER['REDIS_HOST']??null) . ':6379';

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';


/*
| -------------------------------------------------------------------
|  Native Auto-load
| -------------------------------------------------------------------
|
| Nothing to do with config/autoload.php, this allows PHP autoload to work
| for base controllers and some third-party libraries.
|
*/
spl_autoload_register(function($class)
{
 if (strpos($class, 'CI_') !== 0)
 {
  if (file_exists($file = APPPATH . 'core/' . $class . '.php'))
  {
   include $file;
  }
  elseif (file_exists($file = APPPATH . 'libraries/' . $class . '.php'))
  {
   include $file;
  }
 }
});


$config['beanstalkd'] = $_SERVER['BEANSTALK_HOST'] ?? null; // beanstalkd host
$config['scratchSpace'] = $_SERVER['SCRATCH_DIR'] ?? null;

$config['elastic'] = $_SERVER['ELASTIC_HOST'] ?? null;
$config['elasticIndex'] = $_SERVER['ELASTIC_INDEX'] ?? null;

$config['redis'] = ($_SERVER['REDIS_HOST'] ?? null); // elastic ip:port
$config['redisPort'] = "6379";

if(defined('ENVIRONMENT') && (ENVIRONMENT == "local" || $_SERVER['ENVIRONMENT'] == "development")) {
    
  $config["enableCaching"] = false;
}
else {
  $config["enableCaching"] = true;
}

/**
 * paths for external binaries
 */

// if a full path isn't specified, will use system search path
// change to a full path to override location of a program
$config['blenderBinary'] = '/usr/local/bin/blender';
$config['ffmpegBinary'] = '/usr/local/bin/ffmpeg';
$config['exiftoolBinary'] = '/usr/local/bin/exiftool';
$config['ffprobeBinary'] = '/usr/local/bin/ffprobe';
$config['yamdiBinary'] = 'yamdi';
$config['qtfaststartBinary'] = 'qtfaststart';
$config['convertBinary'] = '/usr/local/bin/convert';
$config['gifsicleBinary'] = 'gifsicle';
$config['gnuPlot'] = '/usr/local/bin/gnuplot';
$config['pypdfocr'] = '/usr/local/bin/ocrmypdf';
$config['spatialMedia'] = '/usr/local/bin/spatial';
$config['meshlabPath'] = '/usr/local/bin/meshlab';
$config['nxsBuild'] = '/usr/local/bin/nxsbuild';
$config['nxsEdit'] = '/usr/local/bin/nxsedit';
$config['rtiBuild'] = '/usr/local/bin/rtibuild';
$config['vipsBinary'] = '/usr/local/bin/vips';
$config['shrinkpdf'] = '/usr/local/bin/shrinkpdf';
$config['pdfinfo'] = '/usr/local/bin/pdfinfo';
$config['pdftotext'] = '/usr/local/bin/pdftotext';
$config['identify'] = '/usr/local/bin/identify';
$config['montage'] = '/usr/local/bin/montage';
$config['mogrify'] = '/usr/local/bin/mogrify';
$config['convert'] = '/usr/local/bin/convert';
$config['cziutils'] = '/usr/local/bin/cziutils';
$config['tarrific'] = '/usr/local/bin/tarrific';
$config['3mf2stl'] = '/usr/local/bin/3mf2stl';

// LDAP username and password.
// Application should bind anonymously if not set, or set to blanks.
$config['ldapUsername'] = $_SERVER['LDAP_USERNAME'] ?? null;
$config['ldapPassword'] = $_SERVER['LDAP_PASSWORD'] ?? null;
$config['ldapURI'] = $_SERVER['LDAP_URI'] ?? null;
$config['ldapSearchBase'] = $_SERVER['LDAP_SEARCH_BASE'] ?? null;

$config['shibbolethLogin'] = $_SERVER['SHIBBOLETH_LOGIN'] ?? null;
$config['shibbolethLogout'] = $_SERVER['SHIBBOLETH_LOGOUT'] ?? null;

$config['jwplayer'] = $_SERVER['JWPLAYER_KEY'] ?? null;

$config['googleApi'] = $_SERVER['GOOGLE_API'] ?? null;

$config['missingSiteURL'] = 'http://www.elevatorapp.net';


$config['authHelper'] = $_SERVER['AUTH_HELPER'] ?? "AuthHelper";

$config['oAuthClient'] = $_SERVER['OAUTH_CLIENT'] ?? null;
$config['oAuthSecret'] = $_SERVER['OAUTH_SECRET'] ?? null;
$config['oAuthApplication'] = $_SERVER['OAUTH_APPLICATION'] ?? null;
$config['oAuthDomain'] = $_SERVER['OAUTH_DOMAIN'] ?? null;

$config['oAuthDelegate']['type'] = $_SERVER['OAUTH_DELEGATE_TYPE'] ?? null;
$config['oAuthDelegate']['project_id'] = $_SERVER['OAUTH_DELEGATE_PROJECT_ID'] ?? null;
$config['oAuthDelegate']['private_key_id'] = $_SERVER['OAUTH_DELEGATE_PRIVATE_KEY_ID'] ?? null;
$config['oAuthDelegate']['private_key'] = str_replace("\\n","\n", $_SERVER['OAUTH_DELEGATE_PRIVATE_KEY']?? "");
$config['oAuthDelegate']['client_email'] = $_SERVER['OAUTH_DELEGATE_CLIENT_EMAIL'] ?? null;
$config['oAuthDelegate']['client_id'] = $_SERVER['OAUTH_DELEGATE_CLIENT_ID'] ?? null;
$config['oAuthDelegate']['auth_uri'] = $_SERVER['OAUTH_DELEGATE_AUTH_URI'] ?? null;
$config['oAuthDelegate']['token_uri'] = $_SERVER['OAUTH_DELEGATE_TOKEN_URI'] ?? null;
$config['oAuthDelegate']['auth_provider_x509_cert_url'] = $_SERVER['OAUTH_DELEGATE_AUTH_PROVIDER_X509_CERT_URL'] ?? null;
$config['oAuthDelegate']['client_x509_cert_url'] = $_SERVER['OAUTH_DELEGATE_CLIENT_X509_CERT_URL'] ?? null;

$config['remoteLoginLabel'] = $_SERVER['REMOTE_LOGIN_LABEL'] ?? 'University';
$config['guestLoginLabel'] = $_SERVER['GUEST_LOGIN_LABEL'] ?? 'Guest';

$config['css_override'] = $_SERVER['CSS_OVERRIDE'] ?? 'FALSE';
$config['restrict_hidden_assets'] = $_SERVER['RESTRICT_HIDDEN_ASSETS'] ?? 'FALSE';

$config['sentry_dsn'] = $_SERVER['SENTRY_DSN'] ?? null;

$config['umn_bearer_token'] = $_SERVER['UMN_BEARER_TOKEN'] ?? null;
$config['arcgis_access_token'] = $_SERVER['ARCGIS_ACCESS_TOKEN'] ?? null;

$config['available_themes'] = json_decode($_SERVER['AVAILABLE_THEMES'] ?? '[]', true);

$config['awsQueueRegion'] = $_SERVER['AWS_QUEUEING_REGION'] ?? 'us-east-1';
$config['awsQueueAccessKey'] = $_SERVER['AWS_QUEUEING_ACCESS_KEY_ID'] ?? null;
$config['awsQueueSecretKey'] = $_SERVER['AWS_QUEUEING_SECRET_ACCESS_KEY'] ?? null;
$config['awsQueueJobDefinition'] = $_SERVER['AWS_QUEUEING_JOB_DEFINITION'] ?? 'elevator';
$config['awsQueueJobQueue'] = $_SERVER['AWS_QUEUEING_JOB_QUEUE'] ?? 'PrimaryJobQueue';

$config['shib_authfield'] = $_SERVER['SHIB_AUTH_FIELD'] ?? 'email';
$config['shib_user'] =  [
  // fillable user model attribute => server variable
  'email'       => $_SERVER['SHIB_EMAIL_FIELD'] ?? 'eppn',
  'name'        => $_SERVER['SHIB_NAME_FIELD'] ?? 'displayName',
  'first_name'  => $_SERVER['SHIB_FIRST_NAME'] ?? 'givenName',
  'last_name'   => $_SERVER['SHIB_LAST_NAME'] ?? 'sn',
  'uniqueIdentifier'      => $_SERVER['SHIB_DID'] ?? 'umnDID',
  'emplId'      => $_SERVER['SHIB_EMPL_ID'] ?? 'umnEmplId',
  'umnRegSummary' => $_SERVER['SHIB_REG_SUMMARY'] ?? 'umnRegSummary',
  'eduPersonAffiliation' => $_SERVER['SHIB_AFFILIATION'] ?? 'eduPersonAffiliation',
  'isGuest' => $_SERVER['SHIB_IS_GUEST'] ?? 'isGuest',
];

$config['shib_local_settings']  = [
    'strict' => true,
    'debug' => false,
    'baseurl' => null,
    'sp' => [
        'entityId' => $_SERVER['SHIB_ENTITY_ID'] ?? '',
        'assertionConsumerService' => [
            'url' => $config['base_url'] . ($_SERVER['SHIB_ASSERTION_CONSUMER_URL']?? '/local-sp/Login'),
            'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
        ],
        'singleLogoutService' => [
            'url' =>  $config['base_url'] . ($_SERVER['SHIB_LOGOUT_SERVICE_URL'] ?? '/local-sp/Logout'),
            'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        ],
        'NameIDFormat' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
        'x509cert' => $_SERVER['SHIB_X509_CERT'] ?? '',
        'privateKey' => $_SERVER['SHIB_PRIVATE_KEY'] ?? '',
    ],
    'idp' => [
        'entityId' => $_SERVER['SHIB_IDP_ENTITY'] ?? '',
        'singleSignOnService' => [
            'url' => $_SERVER['SHIB_IDP_SSO'] ?? '',
            'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        ],
        'singleLogoutService' => [
            'url' => $_SERVER['SHIB_IDP_SLO'] ?? '',
            'responseUrl' => $_SERVER['SHIB_IDP_SLO_RESPONSE'] ?? '',
            'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        ],
        'x509certMulti' => [
            'signing' => [
                0 => $_SERVER['SHIB_IDP_X509_SIGNING'] ?? '',
            ],
            'encryption' => [
                0 => $_SERVER['SHIB_IDP_X509_ENCRYPTION'] ?? '',
            ],
        ],
    ],
    'security' => [
        'nameIdEncrypted' => false,
        'authnRequestsSigned' => true,
        'logoutRequestSigned' => false,
        'logoutResponseSigned' => false,
        'signMetadata' => true,
        'wantXMLValidation' => false,
        'wantMessagesSigned' => false,
        'wantAssertionsSigned' => false,
        'wantNameIdEncrypted' => false,
        'requestedAuthnContext' => false,
    ],
    'contactPerson' => [
        'technical' => [
            'givenName' => 'name',
            'emailAddress' => 'no@reply.com',
        ],
        'support' => [
            'givenName' => 'Support',
            'emailAddress' => 'no@reply.com',
        ],
    ],
    'organization' => [
        'en-US' => [
            'name' => 'Name',
            'displayname' => 'Display Name',
            'url' => 'http://url',
        ],
    ],
];

/* End of file config.php */
/* Location: ./application/config/config.php */